const express = require("express")
const register_route = require("./routes/register.route.js")
const users_route = require("./routes/users.route.js")
const createteam_route = require("./routes/createteam.route.js")
const teams_route = require("./routes/teams.route.js")
const addUserToTeam_route = require("./routes/addUserToTeam.route.js")
const deleteUserFromTeam_route = require("./routes/deleteFromTeam.route.js")
const rolecreation_route = require("./routes/rolecreation.route.js")
const getAllRoles_route = require("./routes/getAllRoles.route.js")
const assigningRole_route = require("./routes/assigningRole.route.js")
const userPermission_route = require("./routes/userPermission.route.js")
const cors = require("cors")
const app = express()
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use("/register", register_route)
app.use("/users", users_route)
app.use("/createteam", createteam_route)
app.use("/teams", teams_route)
app.use("/addUserToTeam", addUserToTeam_route)
app.use("/deleteFromTeam", deleteUserFromTeam_route)
app.use("/createRole", rolecreation_route)
app.use("/getAllRoles", getAllRoles_route)
app.use("/assignRole", assigningRole_route)
app.use("/getPermissions", userPermission_route)
module.exports = app